### PR TITLE
Harden style changes

### LINKED ISSUE #558: Bug: Location layer 0.5.3
After updating from 0.5.2 to 0.5.3, an error occurs on forceLocationUpdate:

my code:
```
override fun locationUpdated(location: Location) {
        this.location = location
        locationLayerPlugin?.let {
            it.forceLocationUpdate(this.location)
        }
    }
```

after 3-4 updates i receive error:

```
...Build fingerprint: 'Xiaomi/nikel/nikel:6.0/MRA58K/V9.5.2.0.MBFMIFA:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 22294, tid: 22294, name: beaver.handymap  >>> ru.slybeaver.handymap <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
    x0   0000000000000000  x1   0000007fdedcb4f8  x2   0000000000000043  x3   0000007f8cc8d140
    x4   0000000000430000  x5   0000007f9093c2e0  x6   0000000000000000  x7   0000000000430000
    x8   0000000000000000  x9   0000000000000000  x10  0000007f8cc7c9d0  x11  0000000000000036
    x12  0000000000000001  x13  188e3a5ad68cdef2  x14  0000000000000002  x15  0000000000000000
    x16  188e3a5ad68cdef2  x17  0000007f908c32d0  x18  0000000000000000  x19  0000000000000000
    x20  0000007fdedcb6c8  x21  0000007f90d4b370  x22  0000007f705ef5a8  x23  0000007fdedcbae8
    x24  0000007fdedcbf38  x25  0000007fdedcbbac  x26  0000007fdedcc200  x27  0000007f8cc7a000
    x28  0000007fdedcbb94  x29  0000007fdedcb770  x30  0000007f646fb3ec
    sp   0000007fdedcb650  pc   0000007f646fb3ec  pstate 0000000060000000

backtrace:
    #00 pc 00000000000e73ec  /data/app/ru.slybeaver.handymap-1/lib/arm64/libmapbox-gl.so
    #01 pc 00000000000e91fc  /data/app/ru.slybeaver.handymap-1/lib/arm64/libmapbox-gl.so
    #02 pc 00000000000e9250  /data/app/ru.slybeaver.handymap-1/lib/arm64/libmapbox-gl.so
    #03 pc 0000000001a4b1f8  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.nativeSetFeature(com.mapbox.geojson.Feature)+156)
    #04 pc 0000000001a4bdc8  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(com.mapbox.geojson.Feature)+76)
    #05 pc 0000000001a1b9c8  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.refreshSource()+92)
    #06 pc 0000000001a1dde8  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.setLocationsStale(boolean)+316)
    #07 pc 0000000001a21e40  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin$4.onStaleStateChange(boolean)+164)
    #08 pc 00000000014b3880  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.StaleStateManager.updateLatestLocationTime()+148)
    #09 pc 0000000001a25a74  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.updateLocation(android.location.Location)+136)
    #10 pc 0000000001a26528  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.forceLocationUpdate(android.location.Location)+76)
    #11 pc 000000000011e264  /system/lib64/libart.so (art_quick_invoke_stub+580)
    #12 pc 000000000012e13c  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+176)
    #13 pc 00000000004ccc94  /system/lib64/libart.so (artInterpreterToCompiledCodeBridge+212)
    #14 pc 00000000002a894c  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+480)
    #15 pc 00000000002ab8f0  /system/lib64/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb0EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+268)
    #16 pc 00000000000ddffc  /system/lib64/libart.so (_ZN3art11interpreter15ExecuteGotoImplILb0ELb0EEENS_6JValueEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameES2_+22892)
    #17 pc 0000000000286708  /system/lib64/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+96)
    #18 pc 000000000053e1c4  /system/lib64/libart.so (artQuickToInterpreterBridge+632)
    #19 pc 0000000000127fe4  /system/lib64/libart.so (art_quick_to_interpreter_bridge+100)
    #20 pc 0000000000d9a07c  /data/app/ru.slybeaver.handymap-1/oat/arm64/base.odex (offset 0xd7a000) (void ru.slybeaver.handymap.service.location.LocationEngineService.updateLocation(android.location.Location)+304)
    #21 pc 000000000012814c  /system/lib64/libart.so
```

### PR DESCRIPTION
**Pull request by LukasPaczos**
Fixes #558.

This PR adds a bunch of stress tests that are trying to push as much data as possible while we are reloading the style. Those tests caught a bunch of issues, which are handled with additional state flags and by always using core references to sources and layers instead of local ones.

Let me know if the documentation around state flags is clear enough.

/cc @tobrun for eyes at espresso + map testing

### CODE REVIEW

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt [hunk 1]
```diff
@@ -266,11 +281,11 @@ class LocationLayerPluginTest {
 
         uiController.loopMainThreadForAtLeast(MAP_RENDER_DELAY)
 
-        val point: Point = mapboxMap.queryLocationSourceFeatures(LOCATION_SOURCE)[0].geometry() as Point
+        val point: Point = mapboxMap.querySourceFeatures(LOCATION_SOURCE)[0].geometry() as Point
 
-        Assert.assertThat(plugin.locationEngine, nullValue())
-        Assert.assertEquals(point.latitude(), location.latitude, 0.1)
-        Assert.assertEquals(point.longitude(), location.longitude, 0.1)
+        assertThat(plugin.locationEngine, nullValue())
```
Comment (tobrun) [inline app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: is this equivalent to `assertNull(plugin.locationEgine)`?

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt [hunk 2]
```diff
@@ -266,11 +281,11 @@ class LocationLayerPluginTest {
...
+        assertEquals(point.latitude(), location.latitude, 0.1)
```
Comment (tobrun) [inline app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: The selected delta atm: `The first decimal place is worth up to 11.1 km: it can distinguish the position of one large city from a neighboring large city`. I feel this can be made more accurate:

For example: `The third decimal place is worth up to 110 m: it can identify a large agricultural field or institutional campus.` or
`The fourth decimal place is worth up to 11 m: it can identify a parcel of land. It is comparable to the typical accuracy of an uncorrected GPS unit with no interference.`

https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt [hunk 3]
```diff
@@ -284,13 +299,13 @@ class LocationLayerPluginTest {
...
-        Assert.assertEquals(point.latitude(), location.latitude, 0.1)
-        Assert.assertEquals(point.longitude(), location.longitude, 0.1)
+        val point: Point = mapboxMap.querySourceFeatures(LOCATION_SOURCE)[0].geometry() as Point
+        assertEquals(point.latitude(), location.latitude, 0.1)
+        assertEquals(point.longitude(), location.longitude, 0.1)
 
         plugin.isLocationLayerEnabled = false
         uiController.loopMainThreadForAtLeast(MAP_RENDER_DELAY)
-        assertThat(mapboxMap.queryLocationSourceFeatures(LOCATION_SOURCE).isEmpty(), `is`(true))
+        assertThat(mapboxMap.querySourceFeatures(LOCATION_SOURCE).isEmpty(), `is`(true))
```
Comment (tobrun) [inline app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: is this equivalent to `assertTrue`?

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt (hunk 2 above)
Comment (LukasPaczos) [reply app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: My testing revealed, that when zoomed out to approximately `0` the precision can be around two decimal points. For the test not to be flaky, I'm just checking if the point is in a general position of the forced location, as they are mostly being moved from the infinity anyway, leaving the responsibility for precise rendering to the Maps SDK.

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt (hunk 1 above)
Comment (LukasPaczos) [reply app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: Yes, and since that was the approach taken with this test suite before I took over, I think I'm going to stick with it. Going to do some cleanups of those assertions though.

File: app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt (hunk 3 above)
Comment (LukasPaczos) [reply app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPluginTest.kt]: Same as https://github.com/mapbox/mapbox-plugins-android/pull/568#discussion_r200059794.
